[package]
name = "serum-dex-permissioned"
version = "0.5.1"
edition = "2018"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["dex"] }
serum_dex = { path = "../", features = ["no-entrypoint"] }
spl-token = { version = "7.0.0", features = ["no-entrypoint"] }
